
export interface VerificationResult {
  isMatch: boolean;
  confidence: number;
  reason: string;
  extractedName?: string;
  idType?: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}

export enum VerificationStep {
  ID_UPLOAD = 0,
  SELFIE_CAPTURE = 1,
  ANALYZING = 2,
  RESULT = 3,
}

export interface LoanParams {
  amount: number;
  months: number;
}

export interface DocumentAnalysisResult {
  isAuthentic: boolean;
  documentType: 'Payslip' | 'Bank Statement' | 'Other' | 'Unknown';
  extractedIncome: number;
  employerName: string;
  fraudRiskScore: number;
  deviceRiskAnalysis: string;
  notes: string;
}

// --- New Types for Auth & Flow ---

export type CountryCode = 'SG' | 'MY' | 'TH' | 'ID' | 'VN' | 'PH' | 'IN' | 'PK' | 'BD' | 'LK' | 'NP';

export interface CountryConfig {
  code: CountryCode;
  name: string;
  flag: string; // Emoji flag
  currency: string;
  currencySymbol: string;
  phonePrefix: string;
  idName: string; // MyKad, Thai ID, KTP, Aadhaar, CNIC
  legalContext: string;
  minLoan: number;
  maxLoan: number;
  exchangeRate: number; // Simplified relative to RM base for demo
}

export type ApplicationStatus = 'DRAFT' | 'WAITING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'NEEDS_DOCUMENTS' | 'MATCHING_LENDER' | 'LENDER_FOUND';

export type UserRole = 'BORROWER' | 'AGENT_PERSONAL' | 'AGENT_COMPANY' | 'ADMIN';

export interface User {
  id: string;
  mobile: string;
  icNumber: string;
  name: string;
  password: string; // Stored in memory for demo
  country: CountryCode;
  role: UserRole;
  isAdmin?: boolean; // Legacy support
  companyDetails?: {
    name: string;
    regNo: string;
    address: string;
  };
  isVerified?: boolean;
}

export interface LoanApplication {
  id: string;
  userId: string;
  userName: string;
  icNumber: string;
  country: CountryCode;
  amount: number;
  months: number;
  monthlyPayment: number;
  documentResult: DocumentAnalysisResult | null;
  verificationResult: VerificationResult | null;
  status: ApplicationStatus;
  agreementText?: string; // Generated by AI
  isSigned: boolean;
  submittedAt: Date;
  matchedLender?: string; // Assigned by AI
  commissionAllocated?: boolean;
}