import React from 'react';

interface LoanAgreementProps {
  agreementText: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export const LoanAgreement: React.FC<LoanAgreementProps> = ({ agreementText, onConfirm, onCancel }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4">
      <div className="bg-white text-black w-full max-w-4xl h-[90vh] rounded-lg shadow-2xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="bg-gray-100 p-4 border-b border-gray-300 flex justify-between items-center">
          <h2 className="text-xl font-serif font-bold text-gray-800">Legal Loan Agreement</h2>
          <div className="text-xs text-gray-500 uppercase tracking-wide">
            Generated by SAIF-AI Legal Engine
          </div>
        </div>

        {/* Contract Text */}
        <div className="flex-1 overflow-y-auto p-8 font-serif text-sm leading-relaxed whitespace-pre-wrap bg-gray-50">
          {agreementText}
        </div>

        {/* Footer Actions */}
        <div className="p-6 bg-white border-t border-gray-200 flex items-center justify-between">
          <button 
            onClick={onCancel}
            className="px-6 py-2 text-red-600 font-bold hover:bg-red-50 rounded transition-colors"
          >
            Decline
          </button>
          
          <div className="flex items-center gap-4">
             <div className="text-xs text-gray-500 text-right">
               By clicking confirm, you digitally sign<br/>this document under the Electronic Commerce Act 2006.
             </div>
             <button 
              onClick={onConfirm}
              className="px-8 py-3 bg-blue-900 hover:bg-blue-800 text-white font-bold rounded shadow-lg transition-all transform hover:scale-105"
             >
               I AGREE & SIGN
             </button>
          </div>
        </div>
      </div>
    </div>
  );
};
